Traceback (most recent call last):
  File "i:\My Drive\AutomateTheBoringStuffs\Chapter11\chapter11.py", line 5, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
